apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-kubernetes
  namespace: hello-kube
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-kubernetes
  template:
    metadata:
      labels:
        app: hello-kubernetes
    spec:
      serviceAccountName: hellokube
      containers:
        - name: hello-kubernetes
          image: central-quay-registry.apps.snohub.homelab.io/finance/app-dev:v1.10
          ports:
            - containerPort: 8080
          env:
            - name: MESSAGE
              value: "Hello from OpenShift!"
      imagePullSecrets:
        - name: finance-developer-pull-secret
